// src/lib/courseData.js
export const COURSES_DATA = {
    cs: {
        id: 'cs',
        title: 'Shkenca kompjuterike',
        meta: 'Prof. dr. · 6 ECTS · Sem. IV',
        description: 'Hyrje në konceptet themelore të shkencës kompjuterike, duke përfshirë algoritme, struktura të dhënash dhe programim.',
        lessons: [
            { id: 1, title: 'Hyrje në algoritme', description: 'Konceptet bazë dhe rëndësia e algoritmeve.', files: [] },
            { id: 2, title: 'Struktura të dhënash lineare', description: 'Lista, stiva dhe radhë.', files: [] },
            { id: 3, title: 'Struktura të dhënash jo-lineare', description: 'Pema dhe grafe.', files: [] },
            { id: 4, title: 'Algoritme kërkimi dhe renditjeje', description: 'Kërkimi binar dhe sortimi.', files: [] },
            { id: 5, title: 'Kompleksiteti i algoritmeve', description: 'Analiza e kohës dhe hapësirës.', files: [] },
            { id: 6, title: 'Programim dinamik', description: 'Zgjidhja e problemeve komplekse.', files: [] },
            { id: 7, title: 'Algoritme greedy', description: 'Zgjedhja optimale lokale.', files: [] },
            { id: 8, title: 'Teoria e grafëve', description: 'Aplikime dhe algoritme.', files: [] },
            { id: 9, title: 'Struktura të avancuara', description: 'Hash tables dhe heaps.', files: [] },
            { id: 10, title: 'Rishikimi dhe projekti final', description: 'Përmbledhje dhe aplikim praktik.', files: [] },
            { id: 11, title: 'Seminari i avancuar', description: 'Diskutime dhe studime rasti.', files: [] },
            { id: 12, title: 'Projekt praktik', description: 'Implementimi i një sistemi të thjeshtë.', files: [] },
        ],
    },
    discrete: {
        id: 'discrete',
        title: 'Struktura diskrete',
        meta: 'Prof. asoc. · 5 ECTS · Sem. III',
        description: 'Matematika diskrete dhe struktura të dhënash për shkencën kompjuterike.',
        lessons: [
            { id: 1, title: 'Logjika dhe arsyetimi', description: 'Propozicione, operatorë logjikë dhe tabela e vërtetës.', files: [] },
            { id: 2, title: 'Teknikat e provës', description: 'Prova direkte, kundërshtimi, induksioni matematik.', files: [] },
            { id: 3, title: 'Teoria e grupeve', description: 'Operacione me grupe, bashkimi, prerja, komplementi.', files: [] },
            { id: 4, title: 'Relacione dhe funksione', description: 'Relacione, ekuivalenca, funksione dhe injeksione.', files: [] },
            { id: 5, title: 'Teoria e numrave', description: 'Numrat e plotë, GCD, algoritmi i Euklidit.', files: [] },
            { id: 6, title: 'Kombinatorika bazë', description: 'Permutacione, kombinime dhe parimi i shumëzimit.', files: [] },
            { id: 7, title: 'Teknika të avancuara kombinatorike', description: 'Pigeonhole, rekursione, analiza e rasteve.', files: [] },
            { id: 8, title: 'Teoria e grafëve', description: 'Nyje, harqe, rrugë, cikle dhe grafë të lidhur.', files: [] },
            { id: 9, title: 'Algoritme në grafe', description: 'BFS, DFS dhe konceptet bazë të traversal.', files: [] },
            { id: 10, title: 'Automata dhe gjuhë formale', description: 'DFA, NFA dhe gjuhët formale.', files: [] },
            { id: 11, title: 'Kriptografia dhe teoria e informatës', description: 'Kodimi, entropia dhe enkriptimi bazë.', files: [] },
            { id: 12, title: 'Aplikime dhe projekte', description: 'Zbatim praktik i koncepteve dhe rishikim final.', files: [] },
        ]
    },
    signals: {
        id: 'signals',
        title: 'Sisteme dhe sinjale',
        meta: 'Prof. dr. · 6 ECTS · Sem. IV',
        description: 'Analiza dhe përpunimi i sinjaleve dhe sistemeve.',
        lessons: [
            { id: 1, title: 'Hyrje në sinjale dhe sisteme', description: 'Çfarë janë sinjalet dhe sistemet, klasifikimi bazë.', files: [] },
            { id: 2, title: 'Sinjalet në kohë të vazhdueshme', description: 'Sinjale analoge, energjia dhe fuqia.', files: [] },
            { id: 3, title: 'Sinjalet diskrete', description: 'Mostrimi, kvantizimi dhe sinjalet digjitale.', files: [] },
            { id: 4, title: 'Sistemet lineare dhe invariante në kohë (LTI)', description: 'Lineariteti, invarianza dhe përgjigja e sistemit.', files: [] },
            { id: 5, title: 'Konvolucioni', description: 'Operacioni kryesor për analizën e sistemeve.', files: [] },
            { id: 6, title: 'Transformimi Fourier', description: 'Kalimi nga koha në frekuencë.', files: [] },
            { id: 7, title: 'Seritë Fourier', description: 'Analiza e sinjaleve periodike.', files: [] },
            { id: 8, title: 'Transformimi Laplace', description: 'Analiza e sistemeve në domenin kompleks.', files: [] },
            { id: 9, title: 'Transformimi Z', description: 'Analiza e sistemeve diskrete.', files: [] },
            { id: 10, title: 'Filtrimi i sinjaleve', description: 'Filtra low-pass, high-pass dhe aplikimet.', files: [] },
            { id: 11, title: 'Përpunimi i sinjaleve në kohë reale', description: 'DSP dhe aplikime praktike.', files: [] },
            { id: 12, title: 'Aplikime dhe projekt final', description: 'Implementim praktik dhe analizë.', files: [] },
        ],
    },
    algo: {
        id: 'algo',
        title: 'Algoritme dhe struktura të dhënash',
        meta: 'Prof. dr. · 6 ECTS · Sem. III',
        description: 'Algoritme efikasë dhe struktura të dhënash për zgjidhjen e problemeve.',
        lessons: [
            { id: 1, title: 'Hyrje dhe analiza e algoritmeve', description: 'Kompleksiteti kohor dhe hapësinor.', files: [] },
            { id: 2, title: 'Struktura lineare', description: 'Array, lista dhe stack/queue.', files: [] },
            { id: 3, title: 'Rekursioni', description: 'Zgjidhja e problemeve rekursive.', files: [] },
            { id: 4, title: 'Renditja dhe kërkimi', description: 'Sorting dhe searching algoritme.', files: [] },
            { id: 5, title: 'Pemët', description: 'Binary tree, BST dhe traversal.', files: [] },
            { id: 6, title: 'Heap dhe priority queue', description: 'Struktura për optimizim.', files: [] },
            { id: 7, title: 'Hash tables', description: 'Map, collision handling.', files: [] },
            { id: 8, title: 'Grafet bazë', description: 'Representimi dhe traversal (BFS, DFS).', files: [] },
            { id: 9, title: 'Algoritme në grafe', description: 'Shortest path dhe spanning tree.', files: [] },
            { id: 10, title: 'Greedy algoritme', description: 'Zgjedhje lokale optimale.', files: [] },
            { id: 11, title: 'Programim dinamik', description: 'Memoization dhe tabulation.', files: [] },
            { id: 12, title: 'Aplikime dhe projekt', description: 'Implementim praktik dhe analiza.', files: [] }
        ]
    },
    math: {
        id: 'math',
        title: 'Matematikë e aplikuar',
        meta: 'Prof. asoc. · 5 ECTS · Sem. II',
        description: 'Matematika për inxhinieri dhe shkencë kompjuterike.',
        lessons: [
            { id: 1, title: 'Algjebra lineare', description: 'Vektorë, matrica dhe operacione.', files: [] },
            { id: 2, title: 'Sisteme lineare', description: 'Zgjidhja e ekuacioneve lineare.', files: [] },
            { id: 3, title: 'Derivatet', description: 'Ndryshimi dhe aplikimet.', files: [] },
            { id: 4, title: 'Integralet', description: 'Sipërfaqe dhe akumulim.', files: [] },
            { id: 5, title: 'Ekuacione diferenciale', description: 'Modele dinamike.', files: [] },
            { id: 6, title: 'Probabiliteti', description: 'Ngjarje dhe shpërndarje.', files: [] },
            { id: 7, title: 'Statistika', description: 'Analiza e të dhënave.', files: [] },
            { id: 8, title: 'Optimizimi', description: 'Maksimizim dhe minimizim.', files: [] },
            { id: 9, title: 'Transformime', description: 'Fourier dhe Laplace.', files: [] },
            { id: 10, title: 'Analiza numerike', description: 'Metoda kompjuterike.', files: [] },
            { id: 11, title: 'Modele matematike', description: 'Aplikime reale.', files: [] },
            { id: 12, title: 'Projekt dhe rishikim', description: 'Zbatim praktik dhe testim.', files: [] }
        ]
    },
    english: {
        id: 'english',
        title: 'Anglisht teknik',
        meta: 'Lekt. · 3 ECTS · Sem. I',
        description: 'Gjuhë angleze për terminologji teknike dhe komunikim profesional.',
        lessons: [
            { id: 1, title: 'Bazat e anglishtes teknike', description: 'Terminologjia bazë.', files: [] },
            { id: 2, title: 'Fjalori i IT', description: 'Terma teknologjikë.', files: [] },
            { id: 3, title: 'Leximi teknik', description: 'Kuptimi i dokumentacionit.', files: [] },
            { id: 4, title: 'Shkrimi profesional', description: 'Email dhe dokumente.', files: [] },
            { id: 5, title: 'Shkrimi akademik', description: 'Ese dhe raporte.', files: [] },
            { id: 6, title: 'Prezantime', description: 'Të folurit në publik.', files: [] },
            { id: 7, title: 'Komunikimi në ekip', description: 'Diskutime dhe bashkëpunim.', files: [] },
            { id: 8, title: 'Dokumentimi teknik', description: 'Manuale dhe specifikime.', files: [] },
            { id: 9, title: 'Leximi i research papers', description: 'Analiza e artikujve.', files: [] },
            { id: 10, title: 'Intervista teknike', description: 'Pyetje dhe përgjigje.', files: [] },
            { id: 11, title: 'Prezantim projekti', description: 'Pitch dhe demo.', files: [] },
            { id: 12, title: 'Rishikim dhe test', description: 'Përgatitje finale.', files: [] }
        ]
    },
};