// src/lib/courseData.js
export const COURSES_DATA = {
    cs: {
        id: 'cs',
        title: 'Shkenca kompjuterike',
        meta: 'Prof. dr. · 6 ECTS · Sem. IV',
        description: 'Hyrje në konceptet themelore të shkencës kompjuterike, duke përfshirë algoritme, struktura të dhënash dhe programim.',
        lessons: [
            { id: 1, title: 'Hyrje në algoritme', description: 'Konceptet bazë dhe rëndësia e algoritmeve.', files: [] },
            { id: 2, title: 'Struktura të dhënash lineare', description: 'Lista, stiva dhe radhë.', files: [] },
            { id: 3, title: 'Struktura të dhënash jo-lineare', description: 'Pema dhe grafe.', files: [] },
            { id: 4, title: 'Algoritme kërkimi dhe renditjeje', description: 'Kërkimi binar dhe sortimi.', files: [] },
            { id: 5, title: 'Kompleksiteti i algoritmeve', description: 'Analiza e kohës dhe hapësirës.', files: [] },
            { id: 6, title: 'Programim dinamik', description: 'Zgjidhja e problemeve komplekse.', files: [] },
            { id: 7, title: 'Algoritme greedy', description: 'Zgjedhja optimale lokale.', files: [] },
            { id: 8, title: 'Teoria e grafëve', description: 'Aplikime dhe algoritme.', files: [] },
            { id: 9, title: 'Struktura të avancuara', description: 'Hash tables dhe heaps.', files: [] },
            { id: 10, title: 'Rishikimi dhe projekti final', description: 'Përmbledhje dhe aplikim praktik.', files: [] },
            { id: 11, title: 'Seminari i avancuar', description: 'Diskutime dhe studime rasti.', files: [] },
            { id: 12, title: 'Projekt praktik', description: 'Implementimi i një sistemi të thjeshtë.', files: [] },
        ],
    },
    discrete: {
        id: 'discrete',
        title: 'Struktura diskrete',
        meta: 'Prof. asoc. · 5 ECTS · Sem. III',
        description: 'Matematika diskrete dhe struktura të dhënash për shkencën kompjuterike.',
        lessons: [
            { id: 1, title: 'Logjika dhe prova', description: 'Bazat e logjikës dhe provave matematike.', files: [] },
            { id: 2, title: 'Teoria e grupeve', description: 'Operacione dhe struktura.', files: [] },
            { id: 3, title: 'Teoria e numrave', description: 'Numra të plotë dhe algoritme.', files: [] },
            { id: 4, title: 'Grafe dhe relacione', description: 'Modele dhe aplikime.', files: [] },
            { id: 5, title: 'Struktura kombinatorike', description: 'Permutacione dhe kombinime.', files: [] },
            { id: 6, title: 'Algoritme kombinatorikë', description: 'Zgjidhja e problemeve.', files: [] },
            { id: 7, title: 'Automata dhe gjuhë', description: 'Modele llogaritëse.', files: [] },
            { id: 8, title: 'Teoria e informatës', description: 'Entropia dhe kodimi.', files: [] },
            { id: 9, title: 'Kriptografia bazë', description: 'Siguria dhe enkriptimi.', files: [] },
            { id: 10, title: 'Aplikime praktike', description: 'Projekte dhe rishikim.', files: [] },
        ],
    },
    signals: {
        id: 'signals',
        title: 'Sisteme dhe sinjale',
        meta: 'Prof. dr. · 6 ECTS · Sem. IV',
        description: 'Analiza dhe përpunimi i sinjaleve dhe sistemeve.',
        lessons: [
            { id: 1, title: 'Hyrje në sinjale', description: 'Konceptet themelore dhe llojet.', files: [] },
            { id: 2, title: 'Transformimi Fourier', description: 'Analiza në domenin e frekuencës.', files: [] },
            { id: 3, title: 'Sisteme lineare', description: 'Modele dhe përgjigje.', files: [] },
            { id: 4, title: 'Filtrimi', description: 'Filtra analogë dhe dixhitalë.', files: [] },
            { id: 5, title: 'Sinjalet diskrete', description: 'Mostrimi dhe kvantizimi.', files: [] },
            { id: 6, title: 'Transformimi Z', description: 'Analiza e sistemeve diskrete.', files: [] },
            { id: 7, title: 'Përpunimi i imazheve', description: 'Filtrimi dhe analiza.', files: [] },
            { id: 8, title: 'Sinjalet në kohë reale', description: 'Aplikime praktike.', files: [] },
            { id: 9, title: 'Projekti i sinjaleve', description: 'Implementim dhe analizë.', files: [] },
            { id: 10, title: 'Rishikimi dhe teste', description: 'Përmbledhje dhe vlerësim.', files: [] },
        ],
    },
    algo: {
        id: 'algo',
        title: 'Algoritme dhe struktura të dhënash',
        meta: 'Prof. dr. · 6 ECTS · Sem. III',
        description: 'Algoritme efikasë dhe struktura të dhënash për zgjidhjen e problemeve.',
        lessons: [
            { id: 1, title: 'Hyrje dhe analiza', description: 'Bazat e algoritmeve dhe kompleksitetit.', files: [] },
            { id: 2, title: 'Struktura lineare', description: 'Lista dhe vargje.', files: [] },
            { id: 3, title: 'Pema dhe grafe', description: 'Struktura hierarkike dhe relacione.', files: [] },
            { id: 4, title: 'Algoritme kërkimi', description: 'Kërkimi dhe renditja.', files: [] },
            { id: 5, title: 'Algoritme greedy', description: 'Zgjedhja optimale.', files: [] },
            { id: 6, title: 'Programim dinamik', description: 'Zgjidhja e subproblemeve.', files: [] },
            { id: 7, title: 'Algoritme grafësh', description: 'Shkurtimi dhe rrjetet.', files: [] },
            { id: 8, title: 'Struktura të avancuara', description: 'Hash dhe heaps.', files: [] },
            { id: 9, title: 'Algoritme paralelizimi', description: 'Përpunimi paralel.', files: [] },
            { id: 10, title: 'Projekte dhe aplikime', description: 'Implementim praktik.', files: [] },
        ],
    },
    math: {
        id: 'math',
        title: 'Matematikë e aplikuar',
        meta: 'Prof. asoc. · 5 ECTS · Sem. II',
        description: 'Matematika për inxhinieri dhe shkencë kompjuterike.',
        lessons: [
            { id: 1, title: 'Algjebra lineare', description: 'Vektorë dhe matrica.', files: [] },
            { id: 2, title: 'Ekuacione diferenciale', description: 'Zgjidhja dhe aplikime.', files: [] },
            { id: 3, title: 'Statistika dhe probabiliteti', description: 'Modele dhe analiza.', files: [] },
            { id: 4, title: 'Optimizimi', description: 'Metoda numerike.', files: [] },
            { id: 5, title: 'Transformime', description: 'Fourier dhe Laplace.', files: [] },
            { id: 6, title: 'Matematika diskrete', description: 'Logjika dhe kombinatorikë.', files: [] },
            { id: 7, title: 'Analiza numerike', description: 'Algoritme për zgjidhje.', files: [] },
            { id: 8, title: 'Modele matematike', description: 'Aplikime në inxhinieri.', files: [] },
            { id: 9, title: 'Projekte matematike', description: 'Zgjidhja e problemeve.', files: [] },
            { id: 10, title: 'Rishikimi dhe teste', description: 'Përmbledhje dhe vlerësim.', files: [] },
        ],
    },
    english: {
        id: 'english',
        title: 'Anglisht teknik',
        meta: 'Lekt. · 3 ECTS · Sem. I',
        description: 'Gjuhë angleze për terminologji teknike dhe komunikim profesional.',
        lessons: [
            { id: 1, title: 'Bazat e anglishtes teknike', description: 'Terminologjia themelore.', files: [] },
            { id: 2, title: 'Komunikimi shkencor', description: 'Shkrimi dhe prezantimi.', files: [] },
            { id: 3, title: 'Leximi teknik', description: 'Kuptimi i teksteve.', files: [] },
            { id: 4, title: 'Fjalori i inxhinierisë', description: 'Terma dhe fraza.', files: [] },
            { id: 5, title: 'Prezantime dhe diskutime', description: 'Komunikimi verbal.', files: [] },
            { id: 6, title: 'Shkrimi akademik', description: 'Ese dhe raporte.', files: [] },
            { id: 7, title: 'Gjuhë për projekte', description: 'Dokumentimi teknik.', files: [] },
            { id: 8, title: 'Teste dhe vlerësim', description: 'Praktika dhe rishikim.', files: [] },
        ],
    },
};