/** Përkthime të centralizuara — përdoren me t('path.to.key') */

export const STRINGS = {
  sq: {
    header: {
      skip: 'Kalo te përmbajtja kryesore',
      mainNav: 'Navigimi kryesor',
      navHome: 'Ballina',
      navCourses: 'Lendet e mia',
      navAssignments: 'Detyrat',
      navLibrary: 'Biblioteka',
      navAbout: 'Rreth nesh',
      navContact: 'Na kontaktoni',
      navDashboard: 'Pulti',
      navAdminDashboard: 'Administratori',
      login: 'Hyr',
      logout: 'Dil',
      profileMenu: 'Hap menunë e profilit',
      closeMenu: 'Mbyll menunë',
      openMenu: 'Hap menunë',
      languageMenu: 'Zgjidh gjuhën',
      languageSq: 'Shqip',
      languageEn: 'English',
      roleLabel: 'Roli (demo)',
      roleGuest: 'Vizitor',
      roleStudent: 'Student',

      roleAdmin: 'Administrator',
      profile: 'Profili',
      accountSettings: 'Cilësimet e llogarisë',
      grades: 'Notat',
      messages: 'Mesazhet',
      help: 'Ndihmë',
      studentLabel: 'Student',
      profileSub: 'Profili',
      themeLight: 'Modalitet i çelët',
      themeDark: 'Modalitet i errët',
      notifications: 'Njoftimet',
    },
    auth: {
      loginTitle: 'Hyr në Meson',
      loginSubtitle: 'Mirë se u ktheve—vazhdo me kurset dhe detyrat e tua.',
      emailLabel: 'Email',
      passwordLabel: 'Fjalëkalimi',
      forgotPassword: 'Ke harruar fjalëkalimin?',
      rememberMe: 'Më mbaj mend',
      loginSubmit: 'Hyr',
      orContinueWith: 'Ose vazhdo me',
      noAccount: 'Nuk keni llogari?',
      createAccount: 'Krijo llogari',
      emailReq: 'Emaili është i detyrueshëm',
      emailInv: 'Jepni një adresë emaili të vlefshme',
      passReq: 'Fjalëkalimi është i detyrueshëm',
      registerTitle: 'Krijo llogarinë tënde',
      registerSubtitle: 'Bashkohu në Meson për të nisur mësimin—falas për të filluar.',
      firstName: 'Emri',
      lastName: 'Mbiemri',
      schoolEmail: 'Emaili i shkollës',
      confirmPassword: 'Konfirmo fjalëkalimin',
      chooseRoleTitle: 'Zgjidh rolin tënd',
      chooseRoleHint: 'Zgjidh rolin që të përshtatet—kjo përcakton se çfarë mjetesh shikon.',
      roleStudentTitle: 'Student',
      roleStudentSub: 'Ndiq kurse dhe dorëzo detyra.',
      roleStudentH1: 'Kurse & leksione',
      roleStudentH2: 'Detyra & nota',
      roleTeacherTitle: 'Pedagog',
      roleTeacherSub: 'Mëso klasat dhe vlerëso.',
      roleTeacherH1: 'Leksione & vlerësime',
      roleTeacherH2: 'Klasa & feedback',
      roleParentTitle: 'Prind',
      roleParentSub: 'Ndiq progresin e fëmijës.',
      roleParentH1: 'Progresi & lajme',
      roleParentH2: 'Orari & njoftime',
      suggestedRoleText: 'Roli i sugjeruar bazuar në emailin tuaj:',
      suggestedRoleBtn: 'Përdor rolin',
      dismissBtn: 'Hiqe',
      iAgreeTo: 'Pajtohem me',
      termsOfService: 'Kushtet e Shërbimit',
      and: 'dhe',
      privacyPolicy: 'Politikën e Privatësisë',
      termsHint: 'Hap dokumentet më sipër dhe konfirmo me "Lexova dhe kuptova" për të aktivizuar kutinë.',
      registerSubmit: 'Fillo mësimin',
      alreadyHaveAccount: 'Keni tashmë llogari?',
      logIn: 'Hyr',
      errFirstReq: 'Emri është i detyrueshëm',
      errLastReq: 'Mbiemri është i detyrueshëm',
      errPassLength: 'Përdorni të paktën 8 karaktere',
      errPassConfirm: 'Konfirmoni fjalëkalimin',
      errPassMatch: 'Fjalëkalimet nuk përputhen',
      errTermsMsg1: 'Hapni Kushtet e Shërbimit dhe Politikën e Privatësisë dhe shtypni "Lexova dhe kuptova" për secilën.',
      errTermsMsg2: 'Duhet të pranoni Kushtet e Shërbimit dhe Politikën e Privatësisë.'
    },
    home: {
      brand: 'Meson LMS',
      slideMore: 'Më shumë',
      heroPrev: 'Slide-i paraprak',
      heroNext: 'Slide-i ardhshëm',
      slides: [
        {
          title: 'Fillo tani',
          subtitle: 'Kurse, detyra dhe progresi yt — në një vend të thjeshtë.',
          cta: 'Regjistrohu',
          secondary: null,
        },
        {
          title: 'Pse ky LMS është më i miri',
          subtitle:
            'Ndërfaqe e shpejtë dhe e qartë, për studentë dhe pedagogë — pa zhurmë.',
          cta: 'Zbulo arsyet',
          secondary: 'Më shumë',
        },
        {
          title: 'Mëso nga kudo',
          subtitle: 'Celular, tablet apo shfletues — përmbajtja gjithmonë me ty.',
          cta: 'Hyr në kurset',
          secondary: 'Më shumë',
        },
        {
          title: 'Për shkolla & universitete',
          subtitle: 'Partnerë, kategori dhe raporte — për institucione.',
          cta: 'Na kontaktoni',
          secondary: 'Më shumë',
        },
      ],
      univOverline: 'Bashkëpunëtorë akademikë',
      univTitle: 'Universitetet në rrjetin tonë',
      univBody:
        'Shembuj nga Kosova dhe Shqipëria — nga UBT në Prishtinë deri te universitetet publike. I njëjti stil kartash si më poshtë.',
      catOverline: 'Kategori',
      catTitle: 'Tema të zgjedhura sipas kategorisë',
      catBody:
        'Përzgjidhni shtigjin tuaj — nga dizajni dhe programimi deri te gjuhët dhe muzika.',
      viewCampuses: 'Shiko kampuset',
      viewCourses: 'Shiko kurse',
      chipPartner: 'Partner',
      chipOffer: 'Ofertë',
      chipSoon: 'Së shpejti',
      chipNew: 'E re',
      searchPlaceholder: 'Kërko kurse, tema ose universitete...',
      stats: {
        students: 'Studentë aktivë',
        courses: 'Kurse online',
        mentors: 'Mentorë ekspertë',
        satisfaction: 'Kënaqësi'
      },
      features: {
        overline: 'Pse ne?',
        title: 'Çfarë e bën Meson ndryshe',
        f1Title: 'Mësim i strukturuar',
        f1Desc: 'Gjithçka e organizuar sipas semestrave dhe moduleve.',
        f2Title: 'Qasje nga kudo',
        f2Desc: 'Mëso nga telefoni, tableti ose kompjuteri yt.',
        f3Title: 'Sistemi i notave',
        f3Desc: 'Ndjekje e detajuar e progresit dhe vlerësimeve.'
      },
      testimonials: {
        title: 'Çfarë thonë përdoruesit tanë',
        items: [
          { name: 'Ardi Shala', role: 'Student, UBT', text: 'Meson më ka ndihmuar shumë në organizimin e kohës dhe materialeve.' },
          { name: 'Dr. Elena Berisha', role: 'Pedagoge, UP', text: 'Një platformë shumë intuitive dhe e lehtë për t’u përdorur për ne dhe studentët.' },
          { name: 'Luan Krasniqi', role: 'Student, UT', text: 'Dizajni është i mrekullueshëm dhe njoftimet vijnë gjithmonë në kohë.' }
        ]
      },
      ctaFinal: {
        title: 'Gati për të filluar rrugëtimin tënd?',
        subtitle: 'Bashkohu me mijëra studentë dhe pedagogë në platformën më moderne të mësimit.',
        btn: 'Krijo llogari falas'
      },
      partnersTitle: 'Institucionet që na besojnë',
      student: {
        overline: 'Pulti yt',
        welcome: 'Mirë se erdhe përsëri',
        continueTitle: 'Vazhdo ku e le',
        continueCourse: 'Hyrje në programim — Moduli 4',
        continueBtn: 'Vazhdo mësimin',
        assignLink: 'Shiko të gjitha detyrat',
        browseTitle: 'Eksploro kurse',
        browseBody: 'Kategori të përzgjedhura për ty.',

        facultyOverline: 'Regjistrimi yt',
        facultyTitle: 'Fakulteti dhe programi',
        facultyBody:
          'Sheh vetëm institucionin ku je i regjistruar — pa lista të tjera universitetesh.',
        facultyName: 'Universiteti UBT',
        facultyMeta: 'Fakulteti i inxhinierisë · Prishtinë',
        facultyProgram: 'Inxhinieri kompjuterike — viti II, semestri IV',
        announcementsTitle: 'Njoftime të shpejta',
        announcement1: 'Mbledhje kursi “Struktura diskrete” — e premte 10:00.',
        announcement2: 'Materialet e javës 7 janë publikuar në “Sisteme dhe sinjale”.',
        viewAllNotifications: 'Shiko të gjitha',
        noNotifications: 'Nuk keni njoftime',
        tasks: {
          panelTitle: 'Detyrat & progresi',
          panelSubtitle: 'Afate, zgjatje dhe sa për qind është përfunduar sipas lëndës.',
          progressLabel: 'gati',
          task1: {
            name: 'Detyrë 3 · Grafe',
            course: 'Struktura diskrete',
            due: 'Afati: 12 prill, 23:59',
            extension: 'Zgjatja: 14 prill (miratuar)',
            progress: '72',
          },
          task2: {
            name: 'Kuiz i shpejtë',
            course: 'Shkenca kompjuterike',
            due: 'Afati: 15 prill, 20:00',
            extension: 'Pa zgjatje',
            progress: '40',
          },
          task3: {
            name: 'Projekt mini · FFT',
            course: 'Sisteme dhe sinjale',
            due: 'Afati: 22 prill',
            extension: 'Zgjatja: 25 prill',
            progress: '15',
          },
        },
        semesters: {
          overline: "PLAN STUDIMI",
          title: "Zgjidh Semestrin",
          body: "Zgjidh semestrin për të parë lëndët e tua",
          semester: 'Semestri '
        },
        subjects: {
          overline: 'Semestri aktual',
          title: 'Lëndët e tua',
          body: 'Hyr te çdo lëndë për materiale, njoftime dhe detyra.',
          chipActive: 'Aktive',
          openSubject: 'Hyr në lëndën',
          cs: {
            title: 'Shkenca kompjuterike',
            meta: 'Prof. dr. · 6 ECTS · Sem. IV',
          },
          discrete: {
            title: 'Struktura diskrete',
            meta: 'Prof. asoc. · 5 ECTS · Sem. III',
          },
          signals: {
            title: 'Sisteme dhe sinjale',
            meta: 'Prof. dr. · 6 ECTS · Sem. IV',
          },
          algo: {
            title: 'Algoritme dhe struktura të dhënash',
            meta: 'Prof. dr. · 6 ECTS · Sem. III',
          },
          math: {
            title: 'Matematikë e aplikuar',
            meta: 'Prof. asoc. · 5 ECTS · Sem. II',
          },
          english: {
            title: 'Anglisht teknik',
            meta: 'Lekt. · 3 ECTS · Sem. I',
          },
        },
      },
      admin: {
        overline: 'Paneli i administratorit',
        title: 'Përmbledhje e shpejtë',
        body: 'Statistika dhe veprime të shpeshta për institucionin.',
        users: 'Përdoruesit',
        browseCategories: 'Katalogu i kurseve sipas kategorisë',
        stats: {
          users: 'Përdorues',
          courses: 'Kurse',
          enrollments: 'Regjistrime'
        },
        services: {
          users: {
            title: 'Menaxhimi i Përdoruesve',
            desc: 'Menaxho llogaritë, rolet dhe qasjen e përdoruesve në platformë.'
          },
          courses: {
            title: 'Menaxhimi i Kurseve',
            desc: 'Krijo kurse të reja, ndrysho përmbajtjen dhe organizo planin mësimor.'
          },
          categories: {
            title: 'Kategoritë',
            desc: 'Organizoni kurset në kategori dhe tema për navigim më të lehtë.'
          },
          enrollments: {
            title: 'Regjistrimet',
            desc: 'Shikoni dhe menaxhoni regjistrimet e studentëve në lëndë.'
          },
          certificates: {
            title: 'Certifikatat',
            desc: 'Menaxho lëshimin e certifikatave dhe vërteto arritjet e studentëve.'
          },
          reports: {
            title: 'Raportet',
            desc: 'Shikoni statistika të detajuara dhe raporte mbi performancën.'
          },
          enter: 'Hyr në shërbim',
          comingSoon: 'Ky modul është në fazën e zhvillimit dhe do të jetë i disponueshëm së shpejti.',
          backToPanel: 'Kthehu te Paneli'
        }
      },
      teacher: {
        overline: 'Paneli i pedagogut',
        title: 'Mirë se erdhe, Profesor',
        body: 'Menaxhoni klasat tuaja dhe ndiqni progresin e studentëve.',
        statClasses: 'Klasat aktive',
        statStudents: 'Studentë gjithsej',
        statPending: 'Detyra për vlerësim',
        manageClasses: 'Menaxho klasat',
        grading: 'Vlerësimet',
        schedule: 'Orari im',
        announcementsTitle: 'Njoftimet e mia',
        announcement1: 'Provimi i ndërmjetëm në "Programim" është caktuar më 20 prill.',
      },
      parent: {
        overline: 'Paneli i prindit',
        title: 'Progresi i fëmijëve',
        body: 'Ndiqni arritjet akademike dhe frekuentimin e fëmijëve tuaj.',
        statChildren: 'Fëmijë në sistem',
        statAverage: 'Mesatarja e përgjithshme',
        statAttendance: 'Frekuentimi',
        viewGrades: 'Shiko notat',
        contactTeachers: 'Kontakto pedagogët',
        childrenList: 'Lista e fëmijëve',
      },
    },
    adminUsers: {
      title: 'Menaxhimi i Përdoruesve',
      subtitle: 'Menaxho llogaritë, rolet dhe statusin e përdoruesve.',
      searchPlaceholder: 'Kërko me emër ose email...',
      table: {
        name: 'Emri & Mbiemri',
        email: 'Email',
        role: 'Roli',
        status: 'Statusi',
        joined: 'Anëtarësuar',
        actions: 'Veprime'
      },
      status: {
        active: 'Aktiv',
        inactive: 'Joaktiv'
      },
      actions: {
        edit: 'Ndrysho',
        deactivate: 'Çaktivizo',
        activate: 'Aktivizo',
        delete: 'Fshij'
      },
      form: {
        addTitle: 'Shto Përdorues të Ri',
        editTitle: 'Ndrysho Përdoruesin',
        firstName: 'Emri',
        lastName: 'Mbiemri',
        email: 'Email',
        password: 'Fjalëkalimi',
        role: 'Roli',
        cancel: 'Anulo',
        save: 'Ruaj',
        creating: 'Duke krijuar...',
        updating: 'Duke ruajtur...'
      },
      noUsers: 'Nuk u gjet asnjë përdorues.',
      errors: {
        fetchFailed: 'Dështoi ngarkimi i përdoruesve. Ju lutem kontrolloni serverin.'
      },
      confirmDelete: 'A jeni i sigurt që dëshironi ta fshini këtë përdorues?'
    },
    adminCourses: {
      title: 'Menaxhimi i Kurseve',
      subtitle: 'Krijo, ndrysho dhe menaxho kurset e platformës.',
      searchPlaceholder: 'Kërko kurse...',
      addTitle: 'Shto Kurs të Ri',
      editTitle: 'Ndrysho Kursin',
      noCourses: 'Nuk u gjet asnjë kurs.',
      table: {
        title: 'Titulli',
        category: 'Kategoria',
        semester: 'Semestri',
        instructor: 'Instruktori',
        actions: 'Veprime'
      },
      form: {
        title: 'Titulli i Kursit',
        description: 'Përshkrimi',
        categoryId: 'Kategoria (ID)',
        semester: 'Semestri',
        imageUrl: 'URL e Fotos',
        credits: 'Kreditet',
        instructorId: 'ID e Instruktorit',
        save: 'Ruaj Kursin',
        creating: 'Duke krijuar...',
        updating: 'Duke ruajtur...'
      }
    },
    about: {
      heroOverline: 'Meson LMS',
      heroTitle: 'Mësimi ynë, i thjeshtë dhe i fuqishëm',
      heroSubtitle:
        'Ndërtojmë një platformë që bashkon studentët, pedagogët dhe institucionet — me fokus te qartësia, besimi dhe rezultatet.',
      ctaGetStarted: 'Fillo tani',
      missionTitle: 'Misioni',
      missionBody:
        'Të ofrojmë një mjedis mësimor dixhital të qartë dhe të aksesueshëm, ku çdo përdorues — student apo pedagog — gjen shpejt atë që i nevojitet dhe ndjek progresin pa humbur kohë.',
      visionTitle: 'Vizioni',
      visionBody:
        'Një rrjet mësimor në rajon ku institucionet bashkëpunojnë lehtë, materialet janë të organizuara dhe komunikimi mbetet profesional dhe i sigurt.',
      whatTitle: 'Çfarë është Meson?',
      whatBody:
        'Meson është një sistem për menaxhimin e mësimit (LMS) për kurse, detyra, vlerësime dhe komunikim brenda institucionit. Gjithçka në një ndërfaqe moderne, të përshtatur për ekrane të ndryshme.',
      featuresTitle: 'Çfarë ofron platforma',
      featureCourses: 'Kurse dhe materiale të strukturuara sipas moduleve dhe semestrit.',
      featureAssignments: 'Detyra me afate, njoftime dhe gjurmim progresi.',
      featureGrades: 'Nota dhe feedback i centralizuar për studentët.',
      featureCommunication: 'Mesazhe dhe njoftime për klasën dhe kursin.',
      teamTitle: 'Ekipi',
      teamSubtitle: 'Një grup i përkushtuar ndaj produktit dhe përdoruesve.',
      team1Name: 'Arben Krasniqi',
      team1Role: 'Product & UX',
      team2Name: 'Drita Berisha',
      team2Role: 'Inxhinieri platformës',
      team3Name: 'Luan Morina',
      team3Role: 'Siguria e të dhënave',
      team4Name: 'Elona Shala',
      team4Role: 'Mbështetje akademike',
      trustTitle: 'Besim dhe privatësi',
      trustBody:
        'Të dhënat trajtohen me kujdes: lidhje të enkriptuara (HTTPS), kontroll aksesi sipas rolit dhe parime të qarta për ruajtjen e informacionit. Privatësia e studentëve dhe institucionit është prioritet.',
      statsTitle: 'Në numra (shembull)',
      statStudents: 'Studentë aktivë',
      statCourses: 'Kurse',
      statInstructors: 'Pedagogë',
      statStudentsVal: '12 400+',
      statCoursesVal: '480+',
      statInstructorsVal: '320+',
      whyTitle: 'Pse Meson?',
      why1Title: 'Ndërfaqe e pastër',
      why1Body: 'Më pak klikime për të arritur te materialet dhe detyrat.',
      why2Title: 'Për institucionet',
      why2Body: 'Roli dhe lejet përshtaten me strukturën tuaj akademike.',
      why3Title: 'Progres i dukshëm',
      why3Body: 'Studentët shohin afate dhe përfundim sipas lëndëve.',
      why4Title: 'Mbështetje',
      why4Body: 'Ekipi ynë përgjigjet në kohë për pyetje teknike dhe përdorimi.',
      ctaFinalTitle: 'Gati të bashkohesh?',
      ctaFinalBody: 'Krijo llogari dhe eksploro kurset dhe mjedisin e Meson.',
      ctaRegister: 'Regjistrohu',
    },
    footer: {
      tagline:
        'Një LMS i fokusuar te përdoruesi: mësim i organizuar, komunikim i qartë dhe ndihmë kur ju nevojitet.',
      quick: 'Shpejt',
      support: 'Mbështetje',
      email: 'Email',
      phone: 'Telefon',
      hours: 'Orari',
      hoursVal: 'Hën–Prem, 09:00–17:00 (CET)',
      office: 'Zyra',
      officeVal: 'Prishtinë, Kosovë\nTiranë, Shqipëri',
      privacy: 'Privatësia',
      terms: 'Kushtet',
      cookies: 'Cookies',
      copy: 'Të gjitha të drejtat e rezervuara.',
      helpNote: 'Ndihmë e shpejtë — përgjigje brenda 24 orëve në ditët e punës.',
    },
    notifications: {
      title: 'Të gjitha njoftimet',
      subtitle: 'Qëndroni të përditësuar me ngjarjet më të fundit.',
      unread: 'Të palexuara',
      all: 'Të gjitha',
      markAllRead: 'Shëno të gjitha të lexuara',
      empty: 'Nuk ka njoftime.',
    },
    semester: {
      back: 'Kthehu te pulti',
      overline: 'LËNDËT E SEMESTRIT',
      title: 'Semestri',
      subtitle: 'Eksploroni dhe menaxhoni lëndët ku jeni të regjistruar për këtë semestër.',
      empty: {
        title: 'Nuk u gjetën lëndë',
        desc: 'Nuk gjetëm lëndë aktive për këtë semestër. Ju lutem kontrolloni më vonë ose kontaktoni administratorin.',
      },
      courseBadge: 'Lënda',
      noDescription: 'Nuk ka përshkrim për këtë lëndë.',
      viewCourse: 'Shiko Kursin',
    },
    courseDetail: {
      noModules: 'Nuk ka module në këtë kurs',
      noLessons: 'Nuk ka leksione në këtë modul',
      teacher: '',
      semester: 'Semestri ',
      level: 'Niveli ',
    },
    lessonDetail: {
      notFound: 'Leksioni nuk u gjet',
      back: 'Kthehu mbrapa',
      backToCourse: 'Kthehu te kursi',
      video: 'Video',
      content: 'Përmbajtja',
      extraMaterial: 'Material shtesë',
      openLink: 'Hap linkun',
      quizzes: 'Quizet',
      noQuizzes: 'Nuk ka quiz në këtë leksion',
      minutes: 'minuta',
      assignments: 'Detyrat',
      noAssignments: 'Nuk ka detyra në këtë leksion',
      deadline: 'Afati: ',
    },
    quiz: {
      finished: 'Quiz i përfunduar!',
      scoreSaved: 'Rezultati juaj u ruajt',
      backToLesson: 'Kthehu te leksioni',
      question: 'Pyetja',
      from: 'nga',
      backBtn: 'Mbrapa',
      submittingBtn: 'Duke dërguar...',
      submitBtn: 'Përfundo Quiz-in',
      nextBtn: 'Tjetër',
      minutes: 'minuta',
    },
    course: {
      notFound: 'Kursi nuk u gjet.',
      backToHome: 'Kthehu në fillim',
      backToSubjects: 'Kthehu te lëndët',
      subjectDetail: 'Detajet e lëndës',
      files: 'skedarë',
      viewLesson: 'Shiko ligjeratën',
      lessons: 'Ligjerata',
      addLesson: 'Shto Ligjeratë',
      addNewLesson: 'Shto Ligjeratë të Re',
      editLesson: 'Ndrysho Ligjeratën',
      lessonTitle: 'Titull Ligjerata',
      lessonDescription: 'Përshkrim',
      completed: 'Përfunduar',
      markComplete: 'Shëno përfunduar',
      progress: 'Përparimi',
      noLessons: 'Nuk ka ligjerata në këtë lëndë. Filloni duke shtuar njërën!',
      enterTitle: 'Ju lutem futni titullin',
      confirmDelete: 'Jeni i sigurt?',
      cancel: 'Anulo',
      save: 'Ruaj',
    },
    contact: {
      title: 'Na kontaktoni',
      header: 'Keni pyetje apo nevojë për ndihmë? Na dërgoni një mesazh.',
      name: 'Emri i plotë',
      email: 'Email adresa',
      role: {
        r: 'Roli juaj',
        r1: 'Student',
        r2: 'Pedagog',
        r3: 'Prind',
      },
      topic: {
        t: 'Tema',
        t1: 'Probleme me qasjen',
        t2: 'Pyetje për kurset',
        t3: 'Pyetje për notat',
        t4: 'Ndihmë teknike',
        t5: 'Pagesat / Faturimi',
        t6: 'Tjetër',
      },
      message: 'Mesazhi juaj',
      btn: 'Dërgo mesazhin',
      clr: 'Pastro',
      alert: 'Mesazhi u dërgua me sukses!',
      link: 'Apo na shkruani direkt në: ',
    },
  },
  en: {
    header: {
      skip: 'Skip to main content',
      mainNav: 'Main navigation',
      navHome: 'Home',
      navCourses: 'My courses',
      navAssignments: 'Assignments',
      navLibrary: 'Library',
      navAbout: 'About',
      navContact: 'Contact Us',
      navDashboard: 'Dashboard',
      navAdminDashboard: 'Admin Dashboard',
      login: 'Log in',
      logout: 'Log out',
      profileMenu: 'Open profile menu',
      closeMenu: 'Close menu',
      openMenu: 'Open menu',
      languageMenu: 'Choose language',
      languageSq: 'Albanian',
      languageEn: 'English',
      roleLabel: 'Role (demo)',
      roleGuest: 'Guest',
      roleStudent: 'Student',

      roleAdmin: 'Admin',
      profile: 'Profile',
      accountSettings: 'Account settings',
      grades: 'Grades',
      messages: 'Messages',
      help: 'Help',
      studentLabel: 'Student',
      profileSub: 'Profile',
      themeLight: 'Light mode',
      themeDark: 'Dark mode',
      notifications: 'Notifications',
    },
    auth: {
      loginTitle: 'Log in to Meson',
      loginSubtitle: 'Welcome back—continue your courses and assignments.',
      emailLabel: 'Email',
      passwordLabel: 'Password',
      forgotPassword: 'Forgot password?',
      rememberMe: 'Remember me',
      loginSubmit: 'Log in',
      orContinueWith: 'Or continue with',
      noAccount: 'Don\'t have an account?',
      createAccount: 'Create account',
      emailReq: 'Email is required',
      emailInv: 'Enter a valid email address',
      passReq: 'Password is required',
      registerTitle: 'Create your account',
      registerSubtitle: 'Join Meson to start learning with structure and support—free to get started.',
      firstName: 'First name',
      lastName: 'Last name',
      schoolEmail: 'School email',
      confirmPassword: 'Confirm password',
      chooseRoleTitle: 'Choose your role',
      chooseRoleHint: 'Pick the role that fits you—this sets which tools you see first.',
      roleStudentTitle: 'Student',
      roleStudentSub: 'Take classes and submit work.',
      roleStudentH1: 'Courses & lessons',
      roleStudentH2: 'Assignments & grades',
      roleTeacherTitle: 'Teacher',
      roleTeacherSub: 'Teach classes and grade work.',
      roleTeacherH1: 'Lessons & assessments',
      roleTeacherH2: 'Classes & feedback',
      roleParentTitle: 'Parent',
      roleParentSub: 'Follow your child’s progress.',
      roleParentH1: 'Progress & news',
      roleParentH2: 'Schedules & updates',
      suggestedRoleText: 'Suggested role based on your email:',
      suggestedRoleBtn: 'Use suggested role',
      dismissBtn: 'Dismiss',
      iAgreeTo: 'I agree to the',
      termsOfService: 'Terms of Service',
      and: 'and',
      privacyPolicy: 'Privacy Policy',
      termsHint: 'Open each document above and confirm with "I have read and understood" to enable the checkbox.',
      registerSubmit: 'Start learning',
      alreadyHaveAccount: 'Already have an account?',
      logIn: 'Log in',
      errFirstReq: 'First name is required',
      errLastReq: 'Last name is required',
      errPassLength: 'Use at least 8 characters',
      errPassConfirm: 'Confirm your password',
      errPassMatch: 'Passwords do not match',
      errTermsMsg1: 'Open the Terms of Service and Privacy Policy and tap "I have read and understood" for each.',
      errTermsMsg2: 'You must agree to the Terms of Service and Privacy Policy.'
    },
    home: {
      brand: 'Meson LMS',
      slideMore: 'More',
      heroPrev: 'Previous slide',
      heroNext: 'Next slide',
      slides: [
        {
          title: 'Get started',
          subtitle: 'Your courses, tasks, and progress — in one simple place.',
          cta: 'Sign up',
          secondary: null,
        },
        {
          title: 'Why this LMS stands out',
          subtitle: 'Fast, clear UI for learners and teachers — without clutter.',
          cta: 'See why',
          secondary: 'More',
        },
        {
          title: 'Learn anywhere',
          subtitle: 'Phone, tablet, or browser — your content follows you.',
          cta: 'Open courses',
          secondary: 'More',
        },
        {
          title: 'For schools & universities',
          subtitle: 'Partners, categories, and reporting — built for institutions.',
          cta: 'Contact us',
          secondary: 'More',
        },
      ],
      univOverline: 'Academic partners',
      univTitle: 'Universities in our network',
      univBody:
        'Examples from Kosovo and Albania — from UBT in Prishtina to major public universities.',
      catOverline: 'Categories',
      catTitle: 'Featured topics by category',
      catBody:
        'Pick your path — from design and coding to languages and music.',
      viewCampuses: 'View campuses',
      viewCourses: 'Browse courses',
      chipPartner: 'Partner',
      chipOffer: 'Sale',
      chipSoon: 'Soon',
      chipNew: 'New',
      searchPlaceholder: 'Search courses, topics or universities...',
      stats: {
        students: 'Active students',
        courses: 'Online courses',
        mentors: 'Expert mentors',
        satisfaction: 'Satisfaction'
      },
      features: {
        overline: 'Why us?',
        title: 'What makes Meson different',
        f1Title: 'Structured learning',
        f1Desc: 'Everything organized by semesters and modules.',
        f2Title: 'Access anywhere',
        f2Desc: 'Learn from your phone, tablet or computer.',
        f3Title: 'Grading system',
        f3Desc: 'Detailed tracking of progress and assessments.'
      },
      testimonials: {
        title: 'What our users say',
        items: [
          { name: 'Ardi Shala', role: 'Student, UBT', text: 'Meson helped me a lot in organizing my time and study materials.' },
          { name: 'Dr. Elena Berisha', role: 'Professor, UP', text: 'A very intuitive platform, easy to use for both us and the students.' },
          { name: 'Luan Krasniqi', role: 'Student, UT', text: 'The design is wonderful and notifications always arrive on time.' }
        ]
      },
      ctaFinal: {
        title: 'Ready to start your journey?',
        subtitle: 'Join thousands of students and teachers on the most modern learning platform.',
        btn: 'Create free account'
      },
      partnersTitle: 'Institutions that trust us',
      student: {
        overline: 'Your dashboard',
        welcome: 'Welcome back',
        continueTitle: 'Continue where you left off',
        continueCourse: 'Intro to programming — Module 4',
        continueBtn: 'Resume learning',
        assignLink: 'View all assignments',
        browseTitle: 'Explore courses',
        browseBody: 'Hand-picked categories for you.',
        facultyOverline: 'Your enrolment',
        facultyTitle: 'Faculty and programme',
        facultyBody:
          'Only the institution you’re registered with — no other university list.',
        facultyName: 'University of Business and Technology (UBT)',
        facultyMeta: 'Faculty of Engineering · Prishtina',
        facultyProgram: 'Computer Engineering — Year II, Semester IV',
        announcementsTitle: 'Quick notices',
        announcement1: 'Discrete Structures office hour — Friday 10:00.',
        announcement2: 'Week 7 materials are up in Signals and Systems.',
        viewAllNotifications: 'View all',
        noNotifications: 'You have no notifications',
        tasks: {
          panelTitle: 'Tasks & progress',
          panelSubtitle: 'Deadlines, extensions, and completion by module.',
          progressLabel: 'done',
          task1: {
            name: 'Assignment 3 · Graphs',
            course: 'Discrete structures',
            due: 'Due: 12 Apr, 23:59',
            extension: 'Extended to: 14 Apr (approved)',
            progress: '72',
          },
          task2: {
            name: 'Quick quiz',
            course: 'Computer science',
            due: 'Due: 15 Apr, 20:00',
            extension: 'No extension',
            progress: '40',
          },
          task3: {
            name: 'Mini project · FFT',
            course: 'Signals and systems',
            due: 'Due: 22 Apr',
            extension: 'Extended to: 25 Apr',
            progress: '15',
          },
        },
        semesters: {
          overline: "STUDY PLAN",
          title: "Select Semester",
          body: "Choose a semester to view your courses",
          semester: 'Semester '
        },
        subjects: {
          overline: 'Current semester',
          title: 'Your modules',
          body: 'Open any module for materials, notices, and assignments.',
          chipActive: 'Active',
          openSubject: 'Open module',
          cs: {
            title: 'Computer science',
            meta: 'Prof. · 6 ECTS · Sem. IV',
          },
          discrete: {
            title: 'Discrete structures',
            meta: 'Assoc. prof. · 5 ECTS · Sem. III',
          },
          signals: {
            title: 'Signals and systems',
            meta: 'Prof. · 6 ECTS · Sem. IV',
          },
          algo: {
            title: 'Algorithms and data structures',
            meta: 'Prof. · 6 ECTS · Sem. III',
          },
          math: {
            title: 'Applied mathematics',
            meta: 'Assoc. prof. · 5 ECTS · Sem. II',
          },
          english: {
            title: 'Technical English',
            meta: 'Lecturer · 3 ECTS · Sem. I',
          },
        },
      },
      admin: {
        overline: 'Admin',
        title: 'Quick overview',
        body: 'Key numbers and shortcuts for your institution.',
        users: 'Users',
        browseCategories: 'Course catalog by category',
        stats: {
          users: 'Users',
          courses: 'Courses',
          enrollments: 'Enrollments'
        },
        services: {
          users: {
            title: 'User Management',
            desc: 'Manage user accounts, roles, and platform access.'
          },
          courses: {
            title: 'Course Management',
            desc: 'Create new courses, edit content, and organize curricula.'
          },
          categories: {
            title: 'Categories',
            desc: 'Organize courses into categories and topics for easier navigation.'
          },
          enrollments: {
            title: 'Enrollments',
            desc: 'View and manage student enrollments in various subjects.'
          },
          certificates: {
            title: 'Certificates',
            desc: 'Manage certificate issuance and verify student achievements.'
          },
          reports: {
            title: 'Reports',
            desc: 'View detailed statistics and reports on platform performance.'
          },
          enter: 'Enter service',
          comingSoon: 'This module is under development and will be available soon.',
          backToPanel: 'Back to Panel'
        }
      },
      teacher: {
        overline: 'Teacher Panel',
        title: 'Welcome, Professor',
        body: 'Manage your classes and track student progress.',
        statClasses: 'Active Classes',
        statStudents: 'Total Students',
        statPending: 'Pending Grading',
        manageClasses: 'Manage Classes',
        grading: 'Grading',
        schedule: 'My Schedule',
        announcementsTitle: 'My Announcements',
        announcement1: 'Midterm exam for "Programming" scheduled for April 20th.',
      },
      parent: {
        overline: 'Parent Panel',
        title: "Children's Progress",
        body: "Track your children's academic achievements and attendance.",
        statChildren: 'Children in system',
        statAverage: 'Overall Average',
        statAttendance: 'Attendance',
        viewGrades: 'View Grades',
        contactTeachers: 'Contact Teachers',
        childrenList: 'Children List',
      },
    },
    adminUsers: {
      title: 'User Management',
      subtitle: 'Manage user accounts, roles, and status.',
      searchPlaceholder: 'Search by name or email...',
      table: {
        name: 'Name & Surname',
        email: 'Email',
        role: 'Role',
        status: 'Status',
        joined: 'Joined',
        actions: 'Actions'
      },
      status: {
        active: 'Active',
        inactive: 'Inactive'
      },
      actions: {
        edit: 'Edit',
        deactivate: 'Deactivate',
        activate: 'Activate',
        delete: 'Delete'
      },
      form: {
        addTitle: 'Add New User',
        editTitle: 'Edit User',
        firstName: 'First Name',
        lastName: 'Last Name',
        email: 'Email',
        password: 'Password',
        role: 'Role',
        cancel: 'Cancel',
        save: 'Save',
        creating: 'Creating...',
        updating: 'Saving...'
      },
      noUsers: 'No users found.',
      errors: {
        fetchFailed: 'Failed to load users. Please check the server.'
      },
      confirmDelete: 'Are you sure you want to delete this user?'
    },
    adminCourses: {
      title: 'Course Management',
      subtitle: 'Create, edit, and manage platform courses.',
      searchPlaceholder: 'Search courses...',
      addTitle: 'Add New Course',
      editTitle: 'Edit Course',
      noCourses: 'No courses found.',
      table: {
        title: 'Title',
        category: 'Category',
        semester: 'Semester',
        instructor: 'Instructor',
        actions: 'Actions'
      },
      form: {
        title: 'Course Title',
        description: 'Description',
        categoryId: 'Category (ID)',
        semester: 'Semester',
        imageUrl: 'Image URL',
        credits: 'Credits',
        instructorId: 'Instructor ID',
        save: 'Save Course',
        creating: 'Creating...',
        updating: 'Saving...'
      }
    },
    about: {
      heroOverline: 'Meson LMS',
      heroTitle: 'Learning that stays simple — and scales',
      heroSubtitle:
        'We build a platform that connects students, educators, and institutions with clarity, trust, and measurable outcomes.',
      ctaGetStarted: 'Get started',
      missionTitle: 'Mission',
      missionBody:
        'Deliver a clear, accessible digital learning environment where every user — learner or educator — finds what they need quickly and tracks progress without friction.',
      visionTitle: 'Vision',
      visionBody:
        'A regional learning network where institutions collaborate smoothly, content stays organised, and communication remains professional and secure.',
      whatTitle: 'What is Meson?',
      whatBody:
        'Meson is a learning management system for courses, assignments, assessments, and in-institution communication — in one modern interface that works across devices.',
      featuresTitle: 'What the platform includes',
      featureCourses: 'Structured courses and materials by module and term.',
      featureAssignments: 'Tasks with deadlines, notices, and progress tracking.',
      featureGrades: 'Centralised grades and feedback for learners.',
      featureCommunication: 'Messaging and announcements for class and course.',
      teamTitle: 'Team',
      teamSubtitle: 'People focused on product and user success.',
      team1Name: 'Arben Krasniqi',
      team1Role: 'Product & UX',
      team2Name: 'Drita Berisha',
      team2Role: 'Platform engineering',
      team3Name: 'Luan Morina',
      team3Role: 'Data security',
      team4Name: 'Elona Shala',
      team4Role: 'Academic success',
      trustTitle: 'Trust & privacy',
      trustBody:
        'Data is handled carefully: encrypted connections (HTTPS), role-based access, and clear principles for how information is stored. Student and institutional privacy come first.',
      statsTitle: 'By the numbers (illustrative)',
      statStudents: 'Active learners',
      statCourses: 'Courses',
      statInstructors: 'Instructors',
      statStudentsVal: '12,400+',
      statCoursesVal: '480+',
      statInstructorsVal: '320+',
      whyTitle: 'Why Meson?',
      why1Title: 'Clean interface',
      why1Body: 'Fewer clicks to reach materials and assignments.',
      why2Title: 'Built for institutions',
      why2Body: 'Roles and permissions match your academic structure.',
      why3Title: 'Visible progress',
      why3Body: 'Learners see deadlines and completion by subject.',
      why4Title: 'Support',
      why4Body: 'Our team responds quickly to technical and usage questions.',
      ctaFinalTitle: 'Ready to join?',
      ctaFinalBody: 'Create an account and explore courses and the Meson experience.',
      ctaRegister: 'Register',
    },
    footer: {
      tagline:
        'A user-focused LMS: organised learning, clear communication, and help when you need it.',
      quick: 'Quick links',
      support: 'Support',
      email: 'Email',
      phone: 'Phone',
      hours: 'Hours',
      hoursVal: 'Mon–Fri, 09:00–17:00 (CET)',
      office: 'Offices',
      officeVal: 'Prishtina, Kosovo\nTirana, Albania',
      privacy: 'Privacy',
      terms: 'Terms',
      cookies: 'Cookies',
      copy: 'All rights reserved.',
      helpNote: 'Fast help — replies within 24 hours on business days.',
    },
    notifications: {
      title: 'All Notifications',
      subtitle: 'Stay up to date with the latest events.',
      unread: 'Unread',
      all: 'All',
      markAllRead: 'Mark all as read',
      empty: 'No notifications.',
    },
    semester: {
      back: 'Back to Dashboard',
      overline: 'COURSE BROWSER',
      title: 'Semester',
      subtitle: 'Explore and manage your enrolled subjects for this semester.',
      empty: {
        title: 'No Courses Found',
        desc: 'We couldn\'t find any active courses for this semester. Please check back later or contact your administrator.',
      },
      courseBadge: 'Subject',
      noDescription: 'No description provided for this course.',
      viewCourse: 'View Course',
    },
    courseDetail: {
      noModules: 'No modules in this course',
      noLessons: 'No lessons in this module',
      teacher: '',
      semester: 'Semester ',
      level: 'Level ',
    },
    lessonDetail: {
      notFound: 'Lesson not found',
      back: 'Go back',
      backToCourse: 'Back to course',
      video: 'Video',
      content: 'Content',
      extraMaterial: 'Extra material',
      openLink: 'Open link',
      quizzes: 'Quizzes',
      noQuizzes: 'No quizzes in this lesson',
      minutes: 'minutes',
      assignments: 'Assignments',
      noAssignments: 'No assignments in this lesson',
      deadline: 'Deadline: ',
    },
    quiz: {
      finished: 'Quiz finished!',
      scoreSaved: 'Your score was saved',
      backToLesson: 'Back to lesson',
      question: 'Question',
      from: 'of',
      backBtn: 'Back',
      submittingBtn: 'Submitting...',
      submitBtn: 'Finish Quiz',
      nextBtn: 'Next',
      minutes: 'minutes',
    },
    course: {
      notFound: 'Course not found.',
      backToHome: 'Back to home',
      backToSubjects: 'Back to subjects',
      subjectDetail: 'Subject details',
      files: 'files',
      viewLesson: 'View lesson',
      lessons: 'Lessons',
      addLesson: 'Add Lesson',
      addNewLesson: 'Add New Lesson',
      editLesson: 'Edit Lesson',
      lessonTitle: 'Lesson Title',
      lessonDescription: 'Description',
      completed: 'Completed',
      markComplete: 'Mark as complete',
      progress: 'Progress',
      noLessons: 'No lessons in this subject. Start by adding one!',
      enterTitle: 'Please enter the title',
      confirmDelete: 'Are you sure?',
      cancel: 'Cancel',
      save: 'Save',
    },
    contact: {
      title: 'Contact Us',
      header: 'Have questions or need help? Send us a message.',
      name: 'Full name',
      email: 'Email address',
      role: {
        r: 'Your role',
        r1: 'Student',
        r2: 'Teacher',
        r3: 'Parent',
      },
      topic: {
        t: 'Topic',
        t1: 'Access issues',
        t2: 'Course questions',
        t3: 'Grade questions',
        t4: 'Technical support',
        t5: 'Billing / Payments',
        t6: 'Other',
      },
      message: 'Your message',
      btn: 'Send message',
      clr: 'Clear',
      alert: 'Message sent successfully!',
      link: 'Or write to us directly at: ',
    },
  },
}

export function lookupString(locale, path) {
  const keys = path.split('.')
  let node = STRINGS[locale] ?? STRINGS.sq
  for (const k of keys) {
    node = node?.[k]
  }
  if (typeof node === 'string') return node
  if (node == null) return path
  return path
}
