/** Përkthime të centralizuara — përdoren me t('path.to.key') */

export const STRINGS = {
  sq: {
    header: {
      skip: 'Kalo te përmbajtja kryesore',
      mainNav: 'Navigimi kryesor',
      navHome: 'Ballina',
      navCourses: 'Kurset e mia',
      navAssignments: 'Detyrat',
      navLibrary: 'Biblioteka',
      navAbout: 'Rreth nesh',
      login: 'Hyr',
      logout: 'Dil',
      profileMenu: 'Hap menunë e profilit',
      closeMenu: 'Mbyll menunë',
      openMenu: 'Hap menunë',
      languageMenu: 'Zgjidh gjuhën',
      languageSq: 'Shqip',
      languageEn: 'English',
      roleLabel: 'Roli (demo)',
      roleGuest: 'Vizitor',
      roleStudent: 'Student',
      roleAdmin: 'Administrator',
      profile: 'Profili',
      accountSettings: 'Cilësimet e llogarisë',
      grades: 'Notat',
      messages: 'Mesazhet',
      help: 'Ndihmë',
      studentLabel: 'Student',
      profileSub: 'Profili',
      themeLight: 'Modalitet i çelët',
      themeDark: 'Modalitet i errët',
    },
    home: {
      brand: 'Meson LMS',
      slideMore: 'Më shumë',
      heroPrev: 'Slide-i paraprak',
      heroNext: 'Slide-i ardhshëm',
      slides: [
        {
          title: 'Fillo tani',
          subtitle: 'Kurse, detyra dhe progresi yt — në një vend të thjeshtë.',
          cta: 'Regjistrohu',
          secondary: null,
        },
        {
          title: 'Pse ky LMS është më i miri',
          subtitle:
            'Ndërfaqe e shpejtë dhe e qartë, për studentë dhe pedagogë — pa zhurmë.',
          cta: 'Zbulo arsyet',
          secondary: 'Më shumë',
        },
        {
          title: 'Mëso nga kudo',
          subtitle: 'Celular, tablet apo shfletues — përmbajtja gjithmonë me ty.',
          cta: 'Hyr në kurset',
          secondary: 'Më shumë',
        },
        {
          title: 'Për shkolla & universitete',
          subtitle: 'Partnerë, kategori dhe raporte — për institucione.',
          cta: 'Na kontaktoni',
          secondary: 'Më shumë',
        },
      ],
      univOverline: 'Bashkëpunëtorë akademikë',
      univTitle: 'Universitetet në rrjetin tonë',
      univBody:
        'Shembuj nga Kosova dhe Shqipëria — nga UBT në Prishtinë deri te universitetet publike. I njëjti stil kartash si më poshtë.',
      catOverline: 'Kategori',
      catTitle: 'Tema të zgjedhura sipas kategorisë',
      catBody:
        'Përzgjidhni shtigjin tuaj — nga dizajni dhe programimi deri te gjuhët dhe muzika.',
      viewCampuses: 'Shiko kampuset',
      viewCourses: 'Shiko kurse',
      chipPartner: 'Partner',
      chipOffer: 'Ofertë',
      chipSoon: 'Së shpejti',
      chipNew: 'E re',

      unis: {
        t1: {
          title: 'Universiteti UBT',
          meta: 'Prishtinë · Kosovë',
          chipKey: 'partner',
          chipColor: 'primary',
          icon: 'SchoolRounded',
        },
        t2: {
          title: 'Universiteti i Prishtinës',
          meta: 'Prishtinë · Kosovë',
          chipKey: null,
          chipColor: 'default',
          icon: 'SchoolRounded',
        },
        t3: {
          title: 'Universiteti i Tiranës',
          meta: 'Tiranë · Shqipëri',
          chipKey: null,
          chipColor: 'default',
          icon: 'SchoolRounded',
        },
        t4: {
          title: 'Universiteti Politeknik i Tiranës',
          meta: 'Tiranë · Shqipëri',
          chipKey: null,
          chipColor: 'default',
          icon: 'SchoolRounded',
        },
        t5: {
          title: 'Universiteti i Shkodrës',
          meta: 'Shkodër · Shqipëri',
          chipKey: null,
          chipColor: 'default',
          icon: 'SchoolRounded',
        },
        t6: {
          title: 'Universiteti i Prizrenit',
          meta: 'Prizren · Kosovë',
          chipKey: null,
          chipColor: 'default',
          icon: 'SchoolRounded',
        },
        t7: {
          title: 'Kolegji AAB',
          meta: 'Prishtinë · Kosovë',
          chipKey: null,
          chipColor: 'default',
          icon: 'SchoolRounded',
        },
        t8: {
          title: 'Universiteti i Elbasanit',
          meta: 'Elbasan · Shqipëri',
          chipKey: null,
          chipColor: 'default',
          icon: 'SchoolRounded',
        },
      },
      categories:{
        t1: {
          title: 'Histori e artit',
          meta: '-50% · 3 kurse',
          chipKey: 'offer',
          chipColor: 'error',
        },
        t2: {
          title: 'UI & UX',
          meta: 'Së shpejti · 16 kurse',
          chipKey: 'soon',
          chipColor: 'default',
        },
        t3: {
          title: 'Dizajn 3D',
          meta: '4 kurse',
          chipKey: null,
          chipColor: 'default',
        },
        t4: {
          title: 'Media & PR',
          meta: '9 kurse',
          chipKey: null,
          chipColor: 'default',
        },
        t5: {
          title: 'Programim',
          meta: 'E re · 2 kurse',
          chipKey: 'new',
          chipColor: 'success',
        },
        t6: {
          title: 'Muzikë',
          meta: '6 kurse',
          chipKey: null,
          chipColor: 'default',
        },
        t7: {
          title: 'Gjuhë',
          meta: '3 kurse',
          chipKey: null,
          chipColor: 'default',
        },
      },
      student: {
        overline: 'Pulti yt',
        welcome: 'Mirë se erdhe përsëri',
        continueTitle: 'Vazhdo ku e le',
        continueCourse: 'Hyrje në programim — Moduli 4',
        continueBtn: 'Vazhdo mësimin',
        assignLink: 'Shiko të gjitha detyrat',
        browseTitle: 'Eksploro kurse',
        browseBody: 'Kategori të përzgjedhura për ty.',
        dashboardHint:
          'Më poshtë është fakulteti ku je i regjistruar dhe lëndët e semestrit aktual.',
        facultyOverline: 'Regjistrimi yt',
        facultyTitle: 'Fakulteti dhe programi',
        facultyBody:
          'Sheh vetëm institucionin ku je i regjistruar — pa lista të tjera universitetesh.',
        facultyName: 'Universiteti UBT',
        facultyMeta: 'Fakulteti i inxhinierisë · Prishtinë',
        facultyProgram: 'Inxhinieri kompjuterike — viti II, semestri IV',
        announcementsTitle: 'Njoftime të shpejta',
        announcement1: 'Mbledhje kursi “Struktura diskrete” — e premte 10:00.',
        announcement2: 'Materialet e javës 7 janë publikuar në “Sisteme dhe sinjale”.',
        tasks: {
          panelTitle: 'Detyrat & progresi',
          panelSubtitle: 'Afate, zgjatje dhe sa për qind është përfunduar sipas lëndës.',
          progressLabel: 'gati',
          task1: {
            name: 'Detyrë 3 · Grafe',
            course: 'Struktura diskrete',
            due: 'Afati: 12 prill, 23:59',
            extension: 'Zgjatja: 14 prill (miratuar)',
            progress: '72',
          },
          task2: {
            name: 'Kuiz i shpejtë',
            course: 'Shkenca kompjuterike',
            due: 'Afati: 15 prill, 20:00',
            extension: 'Pa zgjatje',
            progress: '40',
          },
          task3: {
            name: 'Projekt mini · FFT',
            course: 'Sisteme dhe sinjale',
            due: 'Afati: 22 prill',
            extension: 'Zgjatja: 25 prill',
            progress: '15',
          },
        },
        subjects: {
          overline: 'Semestri aktual',
          title: 'Lëndët e tua',
          body: 'Hyr te çdo lëndë për materiale, njoftime dhe detyra.',
          chipActive: 'Aktive',
          openSubject: 'Hyr në lëndën',
          cs: {
            title: 'Shkenca kompjuterike',
            meta: 'Prof. dr. · 6 ECTS · Sem. IV',
          },
          discrete: {
            title: 'Struktura diskrete',
            meta: 'Prof. asoc. · 5 ECTS · Sem. III',
          },
          signals: {
            title: 'Sisteme dhe sinjale',
            meta: 'Prof. dr. · 6 ECTS · Sem. IV',
          },
          algo: {
            title: 'Algoritme dhe struktura të dhënash',
            meta: 'Prof. dr. · 6 ECTS · Sem. III',
          },
          math: {
            title: 'Matematikë e aplikuar',
            meta: 'Prof. asoc. · 5 ECTS · Sem. II',
          },
          english: {
            title: 'Anglisht teknik',
            meta: 'Lekt. · 3 ECTS · Sem. I',
          },
        },
      },
      admin: {
        overline: 'Paneli i administratorit',
        title: 'Përmbledhje e shpejtë',
        body: 'Statistika dhe veprime të shpeshta për institucionin.',
        statUsers: 'Përdorues aktivë (30 ditë)',
        statCourses: 'Kurse publike',
        statAssign: 'Detyra të hapura',
        manageCourses: 'Menaxho kurset',
        reports: 'Raporte',
        users: 'Përdoruesit',
        browseCategories: 'Katalogu i kurseve sipas kategorisë',
      },
    },
    about: {
      heroOverline: 'Meson LMS',
      heroTitle: 'Mësimi ynë, i thjeshtë dhe i fuqishëm',
      heroSubtitle:
        'Ndërtojmë një platformë që bashkon studentët, pedagogët dhe institucionet — me fokus te qartësia, besimi dhe rezultatet.',
      ctaGetStarted: 'Fillo tani',
      missionTitle: 'Misioni',
      missionBody:
        'Të ofrojmë një mjedis mësimor dixhital të qartë dhe të aksesueshëm, ku çdo përdorues — student apo pedagog — gjen shpejt atë që i nevojitet dhe ndjek progresin pa humbur kohë.',
      visionTitle: 'Vizioni',
      visionBody:
        'Një rrjet mësimor në rajon ku institucionet bashkëpunojnë lehtë, materialet janë të organizuara dhe komunikimi mbetet profesional dhe i sigurt.',
      whatTitle: 'Çfarë është Meson?',
      whatBody:
        'Meson është një sistem për menaxhimin e mësimit (LMS) për kurse, detyra, vlerësime dhe komunikim brenda institucionit. Gjithçka në një ndërfaqe moderne, të përshtatur për ekrane të ndryshme.',
      featuresTitle: 'Çfarë ofron platforma',
      featureCourses: 'Kurse dhe materiale të strukturuara sipas moduleve dhe semestrit.',
      featureAssignments: 'Detyra me afate, njoftime dhe gjurmim progresi.',
      featureGrades: 'Nota dhe feedback i centralizuar për studentët.',
      featureCommunication: 'Mesazhe dhe njoftime për klasën dhe kursin.',
      teamTitle: 'Ekipi',
      teamSubtitle: 'Një grup i përkushtuar ndaj produktit dhe përdoruesve.',
      team1Name: 'Arben Krasniqi',
      team1Role: 'Product & UX',
      team2Name: 'Drita Berisha',
      team2Role: 'Inxhinieri platformës',
      team3Name: 'Luan Morina',
      team3Role: 'Siguria e të dhënave',
      team4Name: 'Elona Shala',
      team4Role: 'Mbështetje akademike',
      trustTitle: 'Besim dhe privatësi',
      trustBody:
        'Të dhënat trajtohen me kujdes: lidhje të enkriptuara (HTTPS), kontroll aksesi sipas rolit dhe parime të qarta për ruajtjen e informacionit. Privatësia e studentëve dhe institucionit është prioritet.',
      statsTitle: 'Në numra (shembull)',
      statStudents: 'Studentë aktivë',
      statCourses: 'Kurse',
      statInstructors: 'Pedagogë',
      statStudentsVal: '12 400+',
      statCoursesVal: '480+',
      statInstructorsVal: '320+',
      whyTitle: 'Pse Meson?',
      why1Title: 'Ndërfaqe e pastër',
      why1Body: 'Më pak klikime për të arritur te materialet dhe detyrat.',
      why2Title: 'Për institucionet',
      why2Body: 'Roli dhe lejet përshtaten me strukturën tuaj akademike.',
      why3Title: 'Progres i dukshëm',
      why3Body: 'Studentët shohin afate dhe përfundim sipas lëndëve.',
      why4Title: 'Mbështetje',
      why4Body: 'Ekipi ynë përgjigjet në kohë për pyetje teknike dhe përdorimi.',
      ctaFinalTitle: 'Gati të bashkohesh?',
      ctaFinalBody: 'Krijo llogari dhe eksploro kurset dhe mjedisin e Meson.',
      ctaRegister: 'Regjistrohu',
    },
    support:{
      header:{
        h1:'Si mund t\'ju ndihmojmë?',
        h2:'Gjeni përgjigjen në FAQ ose na dërgoni mesazh.',
        faq:'Pyetje të shpeshta'
      },
      faq:{
        q1: 'Si e ndryshoj fjalëkalimin?',
        a1: 'Shko te Cilësimet → Siguria → Ndrysho fjalëkalimin. Do të marrësh një email konfirmimi.',
        q2: 'Si dorëzoj një detyrë?',
        a2:'Hyr në kurs → zgjidh detyrën → ngarko skedarin ose shkruaj përgjigjen → shtyp Dorëzo para afatit.',
        q3: 'Nuk po më hapet kursi, çfarë bëj?',
        a3: 'Provo me një shfletues tjetër ose pastro cache-in. Nëse problemi vazhdon, kontakto mësuesin ose na shkruaj.',
        q4: 'Si shoh notën time?',
        a4: "Shko te kursi → seksioni Notat. Notat shfaqen pasi mësuesi t'i vlerësojë punimet.",
        q5: 'Si regjistrohem në një kurs të ri?',
        a5: 'Shko te Kurset → Shfleto → gjej kursin dhe shtyp Regjistrohu. Disa kurse kërkojnë kod nga mësuesi.',
        q6: 'Si kontaktoj mësuesin tim?',
        a6: 'Hyr në kurs → shtyp butonin Mesazh pranë emrit të mësuesit, ose përdor seksionin Diskutimet.',
      },
      ask:{
        h1:'Nuk gjete përgjigjen?',
        h2:'Na shkruaj dhe t\'ju përgjigjemi brenda 24 orëve.',
        btn:'Na shkruaj'
      },
      form:{
        h1:'Dërgo një mesazh',
        alert:'Mesazhi u dërgua. Do t\'ju kthejmë përgjigje së shpejti.',
        name:'Emri i plotë',
        email:'Adresa e emailit',
        role:'Roli juaj',
        topic:'Tema e mesazhit',
        message:'Mesazhi',
        send:'Dërgo mesazhin',
        clear:'Pastro',
        link:'Mund të na gjeni edhe në ',

      },
      role_options:{
        s:'Student',
        t:'Mesimdhënës',
        p:'Prind',
      },
      topic:{
        a:'Problem hyrje / llogarie',
        c:'Pyetje për kurs',
        g:'Notim / vlerësim',
        t:'Problem teknik',
        p:'Pagesë / abonim',
        o:'Tjetër',
      },
      validate:{
        name:'E detyrueshme',
        email:'Email i pavlefshëm',
        role:'E detyrueshme',
        topic:'E detyrueshme',
        message:'Minimum 15 karaktere'
      }
    },
    footer: {
      tagline:
        'Një LMS i fokusuar te përdoruesi: mësim i organizuar, komunikim i qartë dhe ndihmë kur ju nevojitet.',
      quick: 'Shpejt',
      support: 'Mbështetje',
      supportLink: 'Kontaktoni mbështetjen',
      help:'Ndihmë',
      email: 'Email',
      phone: 'Telefon',
      hours: 'Orari',
      hoursVal: 'Hën–Prem, 09:00–17:00 (CET)',
      office: 'Zyra',
      officeVal: 'Prishtinë, Kosovë\nTiranë, Shqipëri',
      privacy: 'Privatësia',
      terms: 'Kushtet',
      cookies: 'Cookies',
      copy: 'Të gjitha të drejtat e rezervuara.',
      helpNote: 'Ndihmë e shpejtë — përgjigje brenda 24 orëve në ditët e punës.',
    },
    course: {
      notFound: 'Kursi nuk u gjet.',
      backToHome: 'Kthehu në fillim',
      backToSubjects: 'Kthehu te lëndët',
      subjectDetail: 'Detajet e lëndës',
      files: 'skedarë',
      viewLesson: 'Shiko ligjeratën',
      lessons: 'Ligjerata',
      addLesson: 'Shto Ligjeratë',
      addNewLesson: 'Shto Ligjeratë të Re',
      editLesson: 'Ndrysho Ligjeratën',
      lessonTitle: 'Titull Ligjerata',
      lessonDescription: 'Përshkrim',
      completed: 'Përfunduar',
      markComplete: 'Shëno përfunduar',
      progress: 'Përparimi',
      noLessons: 'Nuk ka ligjerata në këtë lëndë. Filloni duke shtuar njërën!',
      enterTitle: 'Ju lutem futni titullin',
      confirmDelete: 'Jeni i sigurt?',
      cancel: 'Anulo',
      save: 'Ruaj',
    },
  },
  en: {
    header: {
      skip: 'Skip to main content',
      mainNav: 'Main navigation',
      navHome: 'Home',
      navCourses: 'My courses',
      navAssignments: 'Assignments',
      navLibrary: 'Library',
      navAbout: 'About',
      login: 'Log in',
      logout: 'Log out',
      profileMenu: 'Open profile menu',
      closeMenu: 'Close menu',
      openMenu: 'Open menu',
      languageMenu: 'Choose language',
      languageSq: 'Albanian',
      languageEn: 'English',
      roleLabel: 'Role (demo)',
      roleGuest: 'Guest',
      roleStudent: 'Student',
      roleAdmin: 'Admin',
      profile: 'Profile',
      accountSettings: 'Account settings',
      grades: 'Grades',
      messages: 'Messages',
      help: 'Help',
      studentLabel: 'Student',
      profileSub: 'Profile',
      themeLight: 'Light mode',
      themeDark: 'Dark mode',
    },
    home: {
      brand: 'Meson LMS',
      slideMore: 'More',
      heroPrev: 'Previous slide',
      heroNext: 'Next slide',
      unis: {
        t1: {
          title: 'University of Business and Technology (UBT)',
          meta: 'Prishtina · Kosovo',
          chipKey: 'partner',
          chipColor: 'primary',
          icon: 'SchoolRounded',
        },
        t2: {
          title: 'University of Prishtina',
          meta: 'Prishtina · Kosovo',
          chipKey: null,
          chipColor: 'default',
          icon: 'SchoolRounded',
        },
        t3: {
          title: 'University of Tirana',
          meta: 'Tirana · Albania',
          chipKey: null,
          chipColor: 'default',
          icon: 'SchoolRounded',
        },
        t4: {
          title: 'Polytechnic University of Tirana',
          meta: 'Tirana · Albania',
          chipKey: null,
          chipColor: 'default',
          icon: 'SchoolRounded',
        },
        t5: {
          title: 'University of Shkodra',
          meta: 'Shkodra · Albania',
          chipKey: null,
          chipColor: 'default',
          icon: 'SchoolRounded',
        },
        t6: {
          title: 'University of Prizren',
          meta: 'Prizren · Kosovo',
          chipKey: null,
          chipColor: 'default',
          icon: 'SchoolRounded',
        },
        t7: {
          title: 'AAB College',
          meta: 'Prishtina · Kosovo',
          chipKey: null,
          chipColor: 'default',
          icon: 'SchoolRounded',
        },
        t8: {
          title: 'University of Elbasan',
          meta: 'Elbasan · Albania',
          chipKey: null,
          chipColor: 'default',
          icon: 'SchoolRounded',
        },
      },
      categories: {
        t1: {
          title: 'Art History',
          meta: '-50% · 3 courses',
          chipKey: 'offer',
          chipColor: 'error',
        },
        t2: {
          title: 'UI & UX',
          meta: 'Coming soon · 16 courses',
          chipKey: 'soon',
          chipColor: 'default',
        },
        t3: {
          title: '3D Design',
          meta: '4 courses',
          chipKey: null,
          chipColor: 'default',
        },
        t4: {
          title: 'Media & PR',
          meta: '9 courses',
          chipKey: null,
          chipColor: 'default',
        },
        t5: {
          title: 'Programming',
          meta: 'New · 2 courses',
          chipKey: 'new',
          chipColor: 'success',
        },
        t6: {
          title: 'Music',
          meta: '6 courses',
          chipKey: null,
          chipColor: 'default',
        },
        t7: {
          title: 'Languages',
          meta: '3 courses',
          chipKey: null,
          chipColor: 'default',
        },
      },
      slides: [
        {
          title: 'Get started',
          subtitle: 'Your courses, tasks, and progress — in one simple place.',
          cta: 'Sign up',
          secondary: null,
        },
        {
          title: 'Why this LMS stands out',
          subtitle: 'Fast, clear UI for learners and teachers — without clutter.',
          cta: 'See why',
          secondary: 'More',
        },
        {
          title: 'Learn anywhere',
          subtitle: 'Phone, tablet, or browser — your content follows you.',
          cta: 'Open courses',
          secondary: 'More',
        },
        {
          title: 'For schools & universities',
          subtitle: 'Partners, categories, and reporting — built for institutions.',
          cta: 'Contact us',
          secondary: 'More',
        },
      ],
      univOverline: 'Academic partners',
      univTitle: 'Universities in our network',
      univBody:
        'Examples from Kosovo and Albania — from UBT in Prishtina to major public universities.',
      catOverline: 'Categories',
      catTitle: 'Featured topics by category',
      catBody:
        'Pick your path — from design and coding to languages and music.',
      viewCampuses: 'View campuses',
      viewCourses: 'Browse courses',
      chipPartner: 'Partner',
      chipOffer: 'Sale',
      chipSoon: 'Soon',
      chipNew: 'New',

      student: {
        overline: 'Your dashboard',
        welcome: 'Welcome back',
        continueTitle: 'Continue where you left off',
        continueCourse: 'Intro to programming — Module 4',
        continueBtn: 'Resume learning',
        assignLink: 'View all assignments',
        browseTitle: 'Explore courses',
        browseBody: 'Hand-picked categories for you.',
        dashboardHint:
          'Below you’ll see your enrolled faculty and this semester’s courses.',
        facultyOverline: 'Your enrolment',
        facultyTitle: 'Faculty and programme',
        facultyBody:
          'Only the institution you’re registered with — no other university list.',
        facultyName: 'University of Business and Technology (UBT)',
        facultyMeta: 'Faculty of Engineering · Prishtina',
        facultyProgram: 'Computer Engineering — Year II, Semester IV',
        announcementsTitle: 'Quick notices',
        announcement1: 'Discrete Structures office hour — Friday 10:00.',
        announcement2: 'Week 7 materials are up in Signals and Systems.',
        tasks: {
          panelTitle: 'Tasks & progress',
          panelSubtitle: 'Deadlines, extensions, and completion by module.',
          progressLabel: 'done',
          task1: {
            name: 'Assignment 3 · Graphs',
            course: 'Discrete structures',
            due: 'Due: 12 Apr, 23:59',
            extension: 'Extended to: 14 Apr (approved)',
            progress: '72',
          },
          task2: {
            name: 'Quick quiz',
            course: 'Computer science',
            due: 'Due: 15 Apr, 20:00',
            extension: 'No extension',
            progress: '40',
          },
          task3: {
            name: 'Mini project · FFT',
            course: 'Signals and systems',
            due: 'Due: 22 Apr',
            extension: 'Extended to: 25 Apr',
            progress: '15',
          },
        },
        subjects: {
          overline: 'Current semester',
          title: 'Your modules',
          body: 'Open any module for materials, notices, and assignments.',
          chipActive: 'Active',
          openSubject: 'Open module',
          cs: {
            title: 'Computer science',
            meta: 'Prof. · 6 ECTS · Sem. IV',
          },
          discrete: {
            title: 'Discrete structures',
            meta: 'Assoc. prof. · 5 ECTS · Sem. III',
          },
          signals: {
            title: 'Signals and systems',
            meta: 'Prof. · 6 ECTS · Sem. IV',
          },
          algo: {
            title: 'Algorithms and data structures',
            meta: 'Prof. · 6 ECTS · Sem. III',
          },
          math: {
            title: 'Applied mathematics',
            meta: 'Assoc. prof. · 5 ECTS · Sem. II',
          },
          english: {
            title: 'Technical English',
            meta: 'Lecturer · 3 ECTS · Sem. I',
          },
        },
      },
      admin: {
        overline: 'Admin',
        title: 'Quick overview',
        body: 'Key numbers and shortcuts for your institution.',
        statUsers: 'Active users (30 days)',
        statCourses: 'Published courses',
        statAssign: 'Open assignments',
        manageCourses: 'Manage courses',
        reports: 'Reports',
        users: 'Users',
        browseCategories: 'Course catalog by category',
      },
    },
    support: {
      header: {
        h1: 'How can we help you?',
        h2: 'Find the answer in the FAQ or send us a message.',
        faq: 'Frequently Asked Questions'
      },
      faq: {
        q1: 'How do I change my password?',
        a1: 'Go to Settings → Security → Change password. You will receive a confirmation email.',
        q2: 'How do I submit an assignment?',
        a2: 'Enter the course → select the assignment → upload the file or write your answer → click Submit before the deadline.',
        q3: 'The course is not opening, what should I do?',
        a3: 'Try using another browser or clear your cache. If the problem continues, contact your teacher or write to us.',
        q4: 'How can I see my grade?',
        a4: 'Go to the course → Grades section. Grades appear after the teacher evaluates your work.',
        q5: 'How do I enroll in a new course?',
        a5: 'Go to Courses → Browse → find the course and click Enroll. Some courses require a code from the teacher.',
        q6: 'How do I contact my teacher?',
        a6: 'Enter the course → click the Message button next to the teacher’s name, or use the Discussions section.',
      },
      ask: {
        h1: 'Didn’t find the answer?',
        h2: 'Write to us and we will reply within 24 hours.',
        btn: 'Contact us'
      },
      form: {
        h1: 'Send a message',
        alert: 'Message sent. We will get back to you shortly.',
        name: 'Full name',
        email: 'Email address',
        role: 'Your role',
        topic: 'Message topic',
        message: 'Message',
        send: 'Send message',
        clear: 'Clear',
        link: 'You can also find us at ',
      },
      role_options: {
        s: 'Student',
        t: 'Teacher',
        p: 'Parent',
      },
      topic: {
        a: 'Login / account issue',
        c: 'Course question',
        g: 'Grading / evaluation',
        t: 'Technical issue',
        p: 'Payment / subscription',
        o: 'Other',
      },
      validate: {
        name: 'Required',
        email: 'Invalid email',
        role: 'Required',
        topic: 'Required',
        message: 'Minimum 15 characters'
      },
    },
    about: {
      heroOverline: 'Meson LMS',
      heroTitle: 'Learning that stays simple — and scales',
      heroSubtitle:
        'We build a platform that connects students, educators, and institutions with clarity, trust, and measurable outcomes.',
      ctaGetStarted: 'Get started',
      missionTitle: 'Mission',
      missionBody:
        'Deliver a clear, accessible digital learning environment where every user — learner or educator — finds what they need quickly and tracks progress without friction.',
      visionTitle: 'Vision',
      visionBody:
        'A regional learning network where institutions collaborate smoothly, content stays organised, and communication remains professional and secure.',
      whatTitle: 'What is Meson?',
      whatBody:
        'Meson is a learning management system for courses, assignments, assessments, and in-institution communication — in one modern interface that works across devices.',
      featuresTitle: 'What the platform includes',
      featureCourses: 'Structured courses and materials by module and term.',
      featureAssignments: 'Tasks with deadlines, notices, and progress tracking.',
      featureGrades: 'Centralised grades and feedback for learners.',
      featureCommunication: 'Messaging and announcements for class and course.',
      teamTitle: 'Team',
      teamSubtitle: 'People focused on product and user success.',
      team1Name: 'Arben Krasniqi',
      team1Role: 'Product & UX',
      team2Name: 'Drita Berisha',
      team2Role: 'Platform engineering',
      team3Name: 'Luan Morina',
      team3Role: 'Data security',
      team4Name: 'Elona Shala',
      team4Role: 'Academic success',
      trustTitle: 'Trust & privacy',
      trustBody:
        'Data is handled carefully: encrypted connections (HTTPS), role-based access, and clear principles for how information is stored. Student and institutional privacy come first.',
      statsTitle: 'By the numbers (illustrative)',
      statStudents: 'Active learners',
      statCourses: 'Courses',
      statInstructors: 'Instructors',
      statStudentsVal: '12,400+',
      statCoursesVal: '480+',
      statInstructorsVal: '320+',
      whyTitle: 'Why Meson?',
      why1Title: 'Clean interface',
      why1Body: 'Fewer clicks to reach materials and assignments.',
      why2Title: 'Built for institutions',
      why2Body: 'Roles and permissions match your academic structure.',
      why3Title: 'Visible progress',
      why3Body: 'Learners see deadlines and completion by subject.',
      why4Title: 'Support',
      why4Body: 'Our team responds quickly to technical and usage questions.',
      ctaFinalTitle: 'Ready to join?',
      ctaFinalBody: 'Create an account and explore courses and the Meson experience.',
      ctaRegister: 'Register',
    },
    footer: {
      tagline:
        'A user-focused LMS: organised learning, clear communication, and help when you need it.',
      quick: 'Quick links',
      help:'Help',
      supportLink: 'Contact support',
      support: 'Support',
      email: 'Email',
      phone: 'Phone',
      hours: 'Hours',
      hoursVal: 'Mon–Fri, 09:00–17:00 (CET)',
      office: 'Offices',
      officeVal: 'Prishtina, Kosovo\nTirana, Albania',
      privacy: 'Privacy',
      terms: 'Terms',
      cookies: 'Cookies',
      copy: 'All rights reserved.',
      helpNote: 'Fast help — replies within 24 hours on business days.',
    },
    course: {
      notFound: 'Course not found.',
      backToHome: 'Back to home',
      backToSubjects: 'Back to subjects',
      subjectDetail: 'Subject details',
      files: 'files',
      viewLesson: 'View lesson',
      lessons: 'Lessons',
      addLesson: 'Add Lesson',
      addNewLesson: 'Add New Lesson',
      editLesson: 'Edit Lesson',
      lessonTitle: 'Lesson Title',
      lessonDescription: 'Description',
      completed: 'Completed',
      markComplete: 'Mark as complete',
      progress: 'Progress',
      noLessons: 'No lessons in this subject. Start by adding one!',
      enterTitle: 'Please enter the title',
      confirmDelete: 'Are you sure?',
      cancel: 'Cancel',
      save: 'Save',
    },
  },
}

export function lookupString(locale, path) {
  const keys = path.split('.')
  let node = STRINGS[locale] ?? STRINGS.sq
  for (const k of keys) {
    node = node?.[k]
  }
  if (typeof node === 'string') return node
  if (node == null) return path
  return path
}
